---
- hosts: dator
  tasks:
          - name: add neovim ppa
            apt_repository: state=present repo='ppa:neovim-ppa/unstable'

          - name: add spotify signing key
            apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id='BBEBDCB318AD50EC6865090613B00F1FD2C19886'

          - name: add spotify repo
            apt_repository: state=present repo='deb http://repository.spotify.com stable non-free'

          - name: install stuff
            apt: name={{item}} state=installed update_cache=yes
            with_items: 
                  - erlang
                  - clang
                  - exuberant-ctags
                  - git
                  - nautilus-dropbox
                  - neovim
                  - pidgin
                  - pinta
                  - postgresql-9.5
                  - rtorrent
                  - sl
                  - spotify-client
                  - steam
                  - tmux
                  - tree
                  - vlc

          - name: remove stuff
            apt: name={{item}} state=removed 
            with_items: 
                  - thunderbird
                  - rythmbox

          - name: symlink zshrc and neovim config
            file: src={{item.src}} dest={{item.dest}} state=link
            with_items: 
                  - { src: ~/Dropbox/config/zshrc, dest: ~/.zshrc }
                  - { src: ~/Dropbox/config/nvim, dest: ~/.config/nvim }
                  - { src: ~/Dropbox/config/bin, dest: ~/bin }

          - name: make ~/uv directory
            file: path=~/uv state=directory
            become: yes
            become_user: fabian

          - name: install vim plugins
            shell: vim +PluginInstall +qall
            become: yes
            become_user: fabian

          - name: set background image
            shell: gsettings set org.gnome.desktop.background picture-uri file:///home/fabian/Dropbox/config/bakgrundsbild.jpg
            become: yes
            become_user: fabian

          - name: config git
            shell: git config --global {{item.name}} {{item.value}}
            with_items:
                  - { name: 'user.email', value: 'fs@fabianstrom.se' }
                  - { name: 'user.name', value: 'Fabian Ström' }
                  - { name: 'push.default', value: 'matching' }
            become: yes
            become_user: fabian

          - name: inform that dropbox needs to be configured
            debug: msg="Do not forget to configure dropbox"
